services:
  - type: web
    name: greenmarket
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: greenmarket
    autoDeploy: true
